import type { Metadata } from 'next'
import './globals.css'
import ClientOnly from '@/components/ClientOnly'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
            <body>
                <ClientOnly />
                {children}
            </body>
        </html>
    )
}
